version: '3.3'

services:
  # mongodb数据库
  mongodb:
    pid: "blog-mongodb"
    privileged: true
    restart: always
    image: mongo:3.2
    ports:
      - 27017:27017
    volumes:
      # - /home/ubuntu/project/docker/mongodb:/data/db
      - ./mongodb:/data/db
  # wiki-tree 前端
  back-end:
    pid: "blog-backend"
    privileged: true
    restart: always
    image: node:8.0.0
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ../:/app
    working_dir: /app
    command: bash -c "npm install && npm rebuild node-sass --force && npm run build --prod"
  
  # nginx
  nginx:
    pid: "blog-nginx"
    privileged: true
    restart: always
    image: openresty/openresty
    ports: 
      - 80:80
    # external_links:
    volumes:
      - ./nginx/conf:/usr/local/openresty/nginx/conf
      - ./nginx/logs:/usr/local/openresty/nginx/logs
      - ./nginx/html:/usr/local/openresty/nginx/html