version: '3.3'

services:
  # mongodb数据库
  mongodb:
    pid: "node-mongodb"
    privileged: true
    restart: always
    image: mongo:3.2
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      # - /home/ubuntu/project/docker/mongodb:/data/db
      - ../mongodb:/data/db

  # nginx
  nginx:
    pid: "blog-nginx"
    privileged: true
    restart: always
    image: openresty/openresty
    ports: 
      - 8080:80
    # external_links:
    volumes:
      - ./nginx/conf:/usr/local/openresty/nginx/conf
      - ./nginx/log:/usr/local/openresty/nginx/log
      - ./nginx/html:/usr/local/openresty/nginx/html
      - ./nginx:/nginx/pid  
  
  # nodejs 前端
  back-end:
    pid: "node-frontend"
    privileged: true
    restart: always
    image: node:9.8.0
    ports:
      - 8000:8000
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "npm install && node ./src/server.js"
    # wiki-tree 前端
    # back-end:
    #   pid: "blog-backend"
    #   privileged: true
    #   restart: always
    #   image: node:8.0.0
    #   ports:
    #     - 8000:8000
    #   depends_on:
    #     - mongodb
    #   volumes:
    #     - ../:/app
    #   working_dir: /app
    #   command: bash -c "npm install && npm rebuild node-sass --force && npm run build --prod"
