version: '3.3'

services:
  # mongodb数据库
  mongodb:
    pid: "node-mongodb"
    privileged: true
    restart: always
    image: mongo:3.2
    ports:
      - 23333:27017
    volumes:
      # - /home/ubuntu/project/docker/mongodb:/data/db
      - ../mongodb:/data/db

  # nginx
  nginx:
    pid: "nginx"
    privileged: true
    restart: always
    image: openresty/openresty
    depends_on:
      - knowu
      - wiki
    ports: 
      - 8080:80
    # external_links:
    volumes:
      - ./nginx/conf:/usr/local/openresty/nginx/conf
      - ./nginx/log:/usr/local/openresty/nginx/log
      - ./nginx/html:/usr/local/openresty/nginx/html
      - ./nginx:/nginx/pid  
      - /home/ubuntu/sites:/var/sites
  
  # knowu 前端
  knowu:
    pid: "knowu-server"
    privileged: true
    restart: always
    image: node:9.8.0
    expose:
      - 8888:8888
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "npm install & MONGODB=mongodb://mongodb/knowu node ./src/knowu_server.js"

  # knowu 前端
  wiki:
    pid: "wiki-server"
    privileged: true
    restart: always
    image: node:9.8.0
    expose:
      - 8888:8888
    depends_on:
      - mongodb
    volumes:
      - ./:/app
    working_dir: /app
    command: bash -c "npm install & MONGODB=mongodb://mongodb/wiki node ./src/wiki_server.js"